name: dart_leetcode
description: Leetcode practices using dart languange
publish_to: "none"

version: 0.0.0

environment:
  flutter: ^3.22.2
  sdk: ^3.4.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
